// Design fixtures mirror current DashboardSession / VizData fields. No backend calls.
const $ = id => document.getElementById(id);
const icons={Overview:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',Execution:'<path d="M4 12h4l3-8 4 16 3-8h3"/>',Context:'<path d="M4 4h6l2 2 2-2h6v15h-6l-2 2-2-2H4zM12 6v15"/>',Improvement:'<path d="M4 17l6-6 4 3 6-10M14 4h6v6"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[k]}</svg>`;
const names={Overview:'Overview',Execution:'Team Execution',Context:'Team Context',Improvement:'Team Improvement'};
let page='Overview',lastFocus;
const sessionsData=[
 {tool:'Claude',cwd:'teamai-cli',status:'running',promptSummary:'Add provider fallback handling',prompts:['Add provider fallback handling.'],stoppedOutput:'',lastTool:'Read',duration:'12m',promptCount:4,interventions:{interrupt:0,toolReject:0,correction:0},tokens:{input:18000,output:4200,cacheRead:32000,cacheCreation:3000}},
 {tool:'Codex',cwd:'gateway',status:'waiting_for_input',promptSummary:'Review deployment permissions',prompts:['Review deployment permissions.','Check the required permissions before changing the deployment script.'],stoppedOutput:'The permission check is ready for review.',lastTool:'shell',duration:'18m',promptCount:6,interventions:{interrupt:1,toolReject:1,correction:1},tokens:{input:24000,output:6000,cacheRead:41000,cacheCreation:0}},
 {tool:'CodeBuddy',cwd:'teamai-cli',status:'stopped',promptSummary:'Refactor session collector',prompts:['Refactor session collector.'],stoppedOutput:'Updated the collector and ran the targeted tests.',lastTool:'Bash',duration:'9m',promptCount:3,interventions:{interrupt:0,toolReject:0,correction:1},tokens:{input:12000,output:3100,cacheRead:20000,cacheCreation:1000}},
 {tool:'OpenCode',cwd:'gateway',status:'error',promptSummary:'Investigate retry timeout',prompts:['Investigate retry timeout.'],stoppedOutput:'The request failed with a timeout.',lastTool:'bash',duration:'7m',promptCount:2,interventions:{interrupt:0,toolReject:0,correction:0},tokens:{input:9000,output:1500,cacheRead:5000,cacheCreation:0}},
 {tool:'Codex',cwd:'teamai-cli',status:'idle',promptSummary:'Document provider setup',prompts:['Document provider setup.'],stoppedOutput:'Added provider setup instructions.',lastTool:'apply_patch',duration:'15m',promptCount:2,interventions:{interrupt:0,toolReject:0,correction:0},tokens:{input:11000,output:2300,cacheRead:15000,cacheCreation:0}}
];
const labels={running:'Working',waiting_for_input:'Your turn',error:'Error',idle:'Idle',stopped:'Ended'};
const coverage=[['Skills',24,18],['Rules',18,15],['Docs',62,51],['Learnings',16,12]];
// Sample total estimated session costs / sessions with cost data, not cost per request.
const sessionCost=(total, sessions)=>`$${(total/sessions).toFixed(3)} est.`;
const trends=[['Session success','83%','79%'],['Prompts / session','3.5','4.1'],['Active duration','18m','21m'],['Cost / session',sessionCost(42,100),sessionCost(48,100)],['Cache read share','62%','58%'],['Correction rate','12%','16%']];
const knowledge=[{title:'Provider setup',type:'Docs',recalls:32,votes:8,date:'Sep 15'},{title:'Release checks',type:'Rules',recalls:24,votes:6,date:'Sep 14'},{title:'Session debugging',type:'Skills',recalls:18,votes:5,date:'Sep 12'},{title:'Legacy setup notes',type:'Docs',recalls:0,votes:0,date:'Never'}];
const count=s=>Object.values(s.interventions).reduce((a,b)=>a+b,0);
const scoped=()=>sessionsData.filter(s=>($('repo').value==='all'||s.cwd===$('repo').value)&&($('agent').value==='all'||s.tool===$('agent').value));
const go=(p,t)=>`<button class="link" data-page="${p}">${t} →</button>`;
const command=c=>`<code class="command">${c.replaceAll('<','&lt;').replaceAll('>','&gt;')}</code>`;
const resource=(t,d,c,verbatim=false)=>`<div class="resource"><h3>${t}</h3><p ${verbatim?'data-verbatim':''}>${d}</p>${c?command(c):''}</div>`;
function overview(){return `<div class="cards"><article class="card"><div class="cardtop">Team Execution ${icon('Execution')}</div><div class="source">Local sessions · sample</div><div class="big summary-value">5<small>sessions on this machine</small></div><div class="statusline"><span class="good">1 working</span><span class="amber">1 your turn</span><span>1 idle · 1 error · 1 ended</span></div><div class="cardfoot">${go('Execution','View sessions')}<span>Skills · rules · agents · hooks · MCP · env</span></div></article><article class="card"><div class="cardtop">Team Context </div><div class="source">KB Health · team repo aggregate · sample</div><div class="big summary-value">80%<small>knowledge coverage · 96 / 120 entries</small></div><div class="statusline"><span>24 entries never recalled</span></div><div class="cardfoot">${go('Context','View KB Health')}<span>Recall · learnings · codebase · teamwiki</span></div></article><article class="card"><div class="cardtop">Team Improvement </div><div class="source">KB Health maintenance candidates · sample</div><div class="big summary-value">8<small>candidates for review</small></div><div class="statusline"><span>2 promotion · 5 prune · 1 stale</span></div><div class="cardfoot">${go('Improvement','View maintenance')}<span>Usage · sessions · dashboard</span></div></article></div>${trendPanel()}${sessionTable(sessionsData)}`}
function trendPanel(){return `<h2 class="section-label">7 days vs prior 7 days <span class="tag">Local · sample</span></h2><div class="trends">${trends.map(([t,v,p])=>`<article class="card trend"><h2>${t}</h2><div class="big">${v}</div>${t==='Cost / session'?'<p class="label cost-note">Average estimated cost per session with cost data</p>':''}<span class="label">prior: ${p}</span></article>`).join('')}</div>`}
function sessionTable(data){return `<section class="panel sessions"><div class="panelhead"><h2>Local sessions <span class="count">${data.length}</span></h2><span class="label">Sample data</span></div><table><thead><tr><th>FIRST USER PROMPT / DIRECTORY</th><th>AI TOOL</th><th>STATUS</th><th>PROMPTS</th><th>INTERVENTIONS</th><th></th></tr></thead><tbody>${data.map(s=>`<tr data-session="${sessionsData.indexOf(s)}"><td><span data-verbatim>${s.promptSummary}</span><small>${s.cwd} · ${s.duration} · Last tool: ${s.lastTool}</small></td><td>${s.tool}</td><td class="${s.status==='waiting_for_input'||s.status==='error'?'amber':s.status==='running'?'good':''}">${labels[s.status]}</td><td>${s.promptCount}</td><td>${count(s)}</td><td><button class="link" data-session="${sessionsData.indexOf(s)}" aria-label="View ${s.promptSummary}">Details ↗</button></td></tr>`).join('')}</tbody></table>${data.length?'':'<div class="empty">No sessions match these filters.</div>'}</section>`}
function execution(){const data=scoped();return `<div class="statusline">${Object.entries(labels).map(([s,l])=>`<span>${data.filter(x=>x.status===s).length} ${l.toLowerCase()}</span>`).join('')}</div>${sessionTable(data)}`}
function knowledgeTable(title,items){return `<section class="panel sessions"><div class="panelhead"><h2>${title}</h2><span class="label">Sample entries</span></div><table><thead><tr><th>ENTRY</th><th>TYPE</th><th>RECALLS</th><th>UPVOTES</th><th>LAST RECALLED</th></tr></thead><tbody>${items.map(k=>`<tr><td>${k.title}</td><td>${k.type}</td><td>${k.recalls}</td><td>${k.votes}</td><td>${k.date}</td></tr>`).join('')}</tbody></table></section>`}
function context(){return `<div class="panel"><div class="panelhead"><h2>Knowledge Base Health</h2><span class="tag">Team repo · aggregated across the team · sample</span></div><div class="resource"><p>120 entries · 96 recalled at least once · 80% coverage</p></div></div><div class="inventory">${coverage.map(([t,total,covered])=>`<article class="card"><h2>${t}</h2><div class="big">${Math.round(covered/total*100)}%</div><div class="metric-line"><span>${covered} / ${total} recalled</span></div><div class="track"><i style="width:${covered/total*100}%"></i></div></article>`).join('')}</div>${knowledgeTable('Top recalled entries',knowledge.filter(k=>k.recalls))}${knowledgeTable('Silent entries',knowledge.filter(k=>!k.recalls))}<div class="two"><section class="panel"><div class="panelhead"><h2>Monthly recall activity</h2><span class="label">Sample</span></div><div class="resource">${[['July',64],['August',88],['September',72]].map(([m,n])=>`<div class="metric-line"><span>${m}</span><b>${n} recalls</b></div><div class="track"><i style="width:${n}%"></i></div>`).join('')}</div></section><section class="panel"><div class="panelhead"><h2>Recall & maintenance</h2><span class="tag">CLI</span></div>${resource('Team knowledge recall','Recall is off by default and must be explicitly enabled.','teamai recall status\nteamai recall <query>')}<div class="resource">${go('Improvement','View maintenance candidates')}</div></section></div>`}
function improvement(){return `${trendPanel()}<section class="panel"><div class="panelhead"><h2>Maintenance console</h2><span class="tag">KB Health · sample candidates</span></div>${resource('Promotion candidates · 2','Review high-confidence learnings before promoting them to formal knowledge.','teamai recall promote <learning-id> --category skill|rule|doc')}${resource('Prune candidates · 5','Preview low-confidence learnings before deciding whether to archive them.','teamai recall maintenance --prune --dry-run')}${resource('Stale entries · 1','Review stale skills, rules and docs; draft quality updates through the CLI.','teamai recall maintenance --update-quality')}<div class="resource"><p>Commands are shown for reference. No maintenance action is executed by this preview.</p></div></section><div class="two"><section class="panel"><div class="panelhead"><h2>Usage & sessions</h2><span class="tag">CLI</span></div>${resource('Weekly team digest','7-day success, prompt, active-time, estimated cost, cache and correction trends, plus lifetime totals.','teamai digest')}${resource('Session summaries','Save privacy-scrubbed summaries with tool sequences, prompt turns and interventions.','teamai session save')}</section><section class="panel"><div class="panelhead"><h2>Share learnings</h2><span class="tag">Agent skill</span></div>${resource('Friction-based sharing','After a session with interruptions, corrections, tool denials or repeated tool failures, the Stop hook can suggest sharing reusable experience.','/teamai-share-learnings')}</section></div>`}
function render(){ $('nav').innerHTML=Object.keys(names).map(k=>`<button data-page="${k}" class="${page===k?'active':''}" ${page===k?'aria-current="page"':''}>${icon(k)}${names[k]}</button>`).join('');$('crumb').textContent=names[page];$('title').textContent=names[page];document.querySelector('.filters').hidden=page!=='Execution';$('view').innerHTML=({Overview:overview,Execution:execution,Context:context,Improvement:improvement})[page]();localize(document.body)}
function openSession(index){lastFocus=document.activeElement;const s=sessionsData[index];$('detail').innerHTML=`<div class="caption">Local session · sample</div><h2 id="detailTitle" data-verbatim>${s.promptSummary}</h2><span class="tag">${s.tool} · ${labels[s.status]} · ${s.cwd}</span>${resource('Session activity',`${s.duration} · ${s.promptCount} prompt turns · Last tool: ${s.lastTool}`)}${resource('Human interventions',`Interrupt: ${s.interventions.interrupt} · Tool reject: ${s.interventions.toolReject} · Correction: ${s.interventions.correction}`)}${resource('Token usage',`Input: ${s.tokens.input.toLocaleString()} · Output: ${s.tokens.output.toLocaleString()} · Cache read: ${s.tokens.cacheRead.toLocaleString()} · Cache creation: ${s.tokens.cacheCreation.toLocaleString()}`)}${resource('First user prompt',s.prompts[0],null,true)}${s.prompts.length>1?resource('Latest user prompt',s.prompts.at(-1),null,true):''}${resource('AI output',s.stoppedOutput||'No output captured yet.',null,!!s.stoppedOutput)}<p style="margin-top:20px;font-size:12px">Illustrative local content. This preview does not load your prompts or transcripts.</p>`;$('modal').hidden=false;localize($('modal'));document.querySelector('.close').focus()}
function close(){ $('modal').hidden=true;if(lastFocus?.isConnected)lastFocus.focus()}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]'),s=e.target.closest('[data-session]');if(p){page=p.dataset.page;render()}if(s)openSession(+s.dataset.session);if(e.target===$('modal')||e.target.closest('.close'))close()});document.addEventListener('keydown',e=>{if($('modal').hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const f=[...$('modal').querySelectorAll('button')];if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0].focus()}}});for(const id of ['repo','agent'])$(id).onchange=render;initPreferences();render();
